### ISSUE TITLE
登陆是成功了，怎么模拟下单？

### ISSUE THREAD

**Issue by jesson1** [pig6/login_taobao#2]
登陆是成功了，怎么模拟下单？

**Comment by yun12321** [comment]
这个问题解决了么？
我也遇到这个问题了

**Comment by jesson1** [comment]
我分析出淘宝下单的API了，但是没什么用，如果下单过快会被淘宝检测到，同样无法下单



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: yun12321 <notifications@github.com&gt;
发送时间: 2019年11月29日 23:39
收件人: pig6/login_taobao <login_taobao@noreply.github.com&gt;
抄送: jesson1 <1846100778@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[pig6/login_taobao] 登陆是成功了，怎么模拟下单？ (#2)




这个问题解决了么？
 我也遇到这个问题了

**Comment by xiaotiananan** [comment]
我做了PC端模拟下单会被限制不能过快。h5下单就不限制

**Comment by jesson1** [comment]
我后来做了模拟h5下单，同样有时间限制，下单速度太快会被检查到





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: xiaotiananan <notifications@github.com&gt;
发送时间: 2020年2月23日 12:13
收件人: pig6/login_taobao <login_taobao@noreply.github.com&gt;
抄送: jesson1 <1846100778@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[pig6/login_taobao] 登陆是成功了，怎么模拟下单？ (#2)

**Comment by catninelife** [comment]
> 我后来做了模拟h5下单，同样有时间限制，下单速度太快会被检查到 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: xiaotiananan <notifications@github.com&gt; 发送时间: 2020年2月23日 12:13 收件人: pig6/login_taobao <login_taobao@noreply.github.com&gt; 抄送: jesson1 <1846100778@qq.com&gt;, Author <author@noreply.github.com&gt; 主题: 回复：[pig6/login_taobao] 登陆是成功了，怎么模拟下单？ (#2)

活捉真..大佬。能不能分享下你的分析... 我倒是有些想法想去验证。。

**Comment by jesson1** [comment]
时间挺久的了，大概是分为两步，淘宝和天猫大体上类似
首先是点击”立即购买“的时候会发出一个http post请求
URL是这个样子的：
https://buy.taobao.com/auction/buy_now.jhtml?spm=2013.1.20140002.d1.undefined
body参数是这个样子的：

参数信息都可以在商品详情页获取到


上面的请求成功之后会返回一个html页面，这个页面中可以获取到订单数据，可以通过以下的正则表达式获取到：

这是一个json字符串


拿到订单数据之后就可以发出第二个post请求，也就是正式下单
这次请求的url是这个样子：

这里的url里的参数，”pc_submit_url"和“submitref”&nbsp; 在上次请求获得的订单数据中
body参数是这个样子：

请求完了之后，应该就下单成功了。


要注意的是：第一步和第二步直接如果间隔时间太短的话会被淘宝检测出来，最好让程序执行完第一步后暂停个0.8秒






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"catninelife"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月5日(星期四) 晚上10:09
收件人:&nbsp;"pig6/login_taobao"<login_taobao@noreply.github.com&gt;;
抄送:&nbsp;"yjs"<1846100778@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [pig6/login_taobao] 登陆是成功了，怎么模拟下单？ (#2)



 
我后来做了模拟h5下单，同样有时间限制，下单速度太快会被检查到 发自我的iPhone
 …
 ------------------ 原始邮件 ------------------ 发件人: xiaotiananan <notifications@github.com&gt; 发送时间: 2020年2月23日 12:13 收件人: pig6/login_taobao <login_taobao@noreply.github.com&gt; 抄送: jesson1 <1846100778@qq.com&gt;, Author <author@noreply.github.com&gt; 主题: 回复：[pig6/login_taobao] 登陆是成功了，怎么模拟下单？ (#2)
  
活捉真..大佬。能不能分享下你的分析... 我倒是有些想法想去验证。。

**Comment by catninelife** [comment]
> body参数是这个样子的：

谢谢大佬指点..但是你说的下面这些信息都丢失了。。。
“body参数是这个样子的：”
“这次请求的url是这个样子："
...

**Comment by jesson1** [comment]
![Xnip2020-03-06_10-31-05](https://user-images.githubusercontent.com/26702832/76044671-f5fd3780-5f95-11ea-9bec-a2ac2ab92b8f.jpg)

**Comment by ghost** [comment]
> > 我后来做了模拟h5下单，同样有时间限制，下单速度太快会被检查到 发自我的iPhone
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: xiaotiananan <[notifications@github.com](mailto:notifications@github.com)> 发送时间: 2020年2月23日 12:13 收件人: pig6/login_taobao <[login_taobao@noreply.github.com](mailto:login_taobao@noreply.github.com)> 抄送: jesson1 <[1846100778@qq.com](mailto:1846100778@qq.com)>, Author <[author@noreply.github.com](mailto:author@noreply.github.com)> 主题: 回复：[pig6/login_taobao] 登陆是成功了，怎么模拟下单？ (#2)
> 
> 活捉真..大佬。能不能分享下你的分析... 我倒是有些想法想去验证。。

大佬，能不能整合一下，分享你的代码，谢谢

**Comment by jjylovezpp** [comment]
> > body参数是这个样子的：
> 
> 谢谢大佬指点..但是你说的下面这些信息都丢失了。。。
> “body参数是这个样子的：”
> “这次请求的url是这个样子："
> ...

老哥怎么联系你，有些想法想跟你交流下
